### ISSUE TITLE
snapshot_data cron job seems broken

### ISSUE THREAD

**Issue by raivivek** [hargup/WIGI-website#98]
`newest-changes` directory is empty..

**Comment by notconfusing** [comment]
@hargup The saving should happen on line 284 of 
`/home/maximilianklein/WIGI/gender-index-processing-standalone.py`

**Comment by raivivek** [comment]
@hargup `newest-changes` isn't updated.

**Comment by hargup** [comment]
@vivekiitkgp The cron last ran the update script on "Dec 28 12:00:01". Though the output from the `gender-index-processing-standalone.py` is stored anywhere, updating the script to log that too and manually running it again.

**Comment by notconfusing** [comment]
OK the issue is that.... I think i broke it. There was an extra unexpected file "longitude.tar.gz" which I created and it was in `snapshot_data`. The diffing script crashes if it finds unexpect files in the `snapshot_data` dir. Anyway. There is just one more step to do. Which is to move the nikola build process into the script `/home/maximilianklein/Wikidata-Toolkit/wdtk-examples/run_wigi_cron.sh` 

@vivekiitkgp @hargup can you move the may you build nikola into the end of `/home/maximilianklein/Wikidata-Toolkit/wdtk-examples/run_wigi_cron.sh`.  @hargup said this is possible now despite previous issues by just invoiking `sudo su` before building so that nikola has access to the right files.

**Comment by notconfusing** [comment]
@vivekiitkgp this was not fixed. there were two issue that I had to solve: 
1. inserting git pull origin master to update the nikola code was failing because it was waiting for input to unlock the ssh key
2. `/var/www/html` was still pointing to the `manydev/wigi-website/output/` it is now pointing to `maximilianklein/wigi-websits/output`/

**Comment by raivivek** [comment]
Geez! Thanks for fixing the rest. I had no idea about 1 and I thought I fixed the second. :/
